### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "John Doe Doe",
    "email": "test@example.com",
    "password": "password123",
    "confirmPassword": "password123",
    "country": "USA"
}

### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "ikhwan@gmail.com",
    "password": "ikhwan123"
}

### Add Transaction
POST http://localhost:5000/api/transaction/add
Content-Type: application/json

{
    "type": "income",
    "name": "Salary",
    "category": "work",
    "description": "Monthly paycheck",
    "date": "2026-02-09T12:00:00.000Z",
    "images": []
}

### Get Current User Profile
GET http://localhost:5000/api/auth/me


### Get Expense Categories
GET http://localhost:5000/api/transaction/categories
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjUwNTNlMWExYTM5YTFiYzA1ODMzOSIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc3NTQwMDQ2MywiZXhwIjoxNzc1NDA0MDYzfQ.2nBOvQNJ3oScBAtqozjlbYe3E7NXXIfUsjWjwEDMj44


### Test Endpoint
GET http://localhost:5000/test



# DASHBOARD TESTING
### Get Latest Transactions
GET http://localhost:5000/api/dashboard/latest-transactions
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjY3Mzc0MDFmNzczNDkyNDAyYzgwYyIsImVtYWlsIjoiaWtod2FuQGdtYWlsLmNvbSIsImlhdCI6MTc3NTcwNzczNiwiZXhwIjoxNzc1NzExMzM2fQ.aB9DMUyoGe2ZwEJSFkZ51XR4MEkaiIYxik887pObLbM

### Get Balance Summary
GET http://localhost:5000/api/dashboard/balance
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjY3Mzc0MDFmNzczNDkyNDAyYzgwYyIsImVtYWlsIjoiaWtod2FuQGdtYWlsLmNvbSIsImlhdCI6MTc3NTcwNzczNiwiZXhwIjoxNzc1NzExMzM2fQ.aB9DMUyoGe2ZwEJSFkZ51XR4MEkaiIYxik887pObLbM

### Get Expense Breakdown
GET http://localhost:5000/api/dashboard/expense-breakdown
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjY3Mzc0MDFmNzczNDkyNDAyYzgwYyIsImVtYWlsIjoiaWtod2FuQGdtYWlsLmNvbSIsImlhdCI6MTc3NTcwNzczNiwiZXhwIjoxNzc1NzExMzM2fQ.aB9DMUyoGe2ZwEJSFkZ51XR4MEkaiIYxik887pObLbM

### Get Monthly Expenses
GET http://localhost:5000/api/dashboard/monthly-expenses
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjY3Mzc0MDFmNzczNDkyNDAyYzgwYyIsImVtYWlsIjoiaWtod2FuQGdtYWlsLmNvbSIsImlhdCI6MTc3NTcwNzczNiwiZXhwIjoxNzc1NzExMzM2fQ.aB9DMUyoGe2ZwEJSFkZ51XR4MEkaiIYxik887pObLbM
