### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "email": "test@example.com",
    "password": "password123"
}

### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123"
}

### Add Transaction
POST http://localhost:5000/api/transaction/add
Content-Type: application/json

{
    "type": "income",
    "name": "Salary",
    "category": "work",
    "description": "Monthly paycheck",
    "date": "2026-02-09T12:00:00.000Z",
    "images": []
}
